TrajectoryPlannerROS:
  max_vel_x: 0.3 #0.27 = 1kmph  1.67m/s = 6kmph
  min_vel_x: 0.08 #0.05 tried this for a short while
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.0

  acc_lim_theta: 1.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  # goal tolerance
  xy_goal_tolerance: 0.2 #0.4
  yaw_goal_tolerance: 0.2 #0.3

  sim_time: 5.0
  
  holonomic_robot: false
  meter_scoring: true
