# static_map - True if using existing map

global_costmap:
  global_frame: map #odom
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  resolution: 0.05
  static_map: true
  width: 20.0
  height: 20.0
